language: python

python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

install:
    - "wget https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.0.0-SNAPSHOT/openapi-generator-cli-4.0.0-20190225.145928-329.jar"
    - "java -jar openapi-generator-cli-4.0.0-20190225.145928-329.jar generate -i openapis/swagger.yaml -g python -o swagger_client"
    - "cd swagger_client; python setup.py install; cd .."
    - "python setup.py install --force"
    - "pip install -r test-requirements.txt"

script: "py.test -vv tests"
